server:
  port: 8001

mybatis:
  mapper-locations: classpath*:mappers/ct/*/*.xml
## druid访问地址配置
druid:
  login:
    username: root
    password: root
#  allow:
#    ip: 127.0.0.1
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://39.106.39.129:3306/data?useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 1311150301
          type: com.alibaba.druid.pool.xa.DruidXADataSource
          driverClassName: com.mysql.jdbc.Driver
          druid:
            # 初始化连接大小
            initial-size: 3
            #最大连接池数量
            max-active: 8
            # 最小连接池数量
            min-idle: 2
            # 配置获取连接等待超时的时间 单位毫秒
            max-wait: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            min-evictable-idle-time-millis: 30000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            max-evictable-idle-time-millis: 30000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            time-between-eviction-runs-millis: 0
            # 测试连接
            validation-query: select 1
            validation-query-timeout: 10000
            # 获取连接时执行检测，建议关闭，影响性能
            test-on-borrow: false
            # 归还连接时执行检测，建议关闭，影响性能
            test-on-return: false
            # 申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
            test-while-idle: true
            # 打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: true
            max-open-prepared-statements: 100
              #      配置监控统计拦截器 防火墙 日志配置
              #      stat监控数据库性能
              #      wall  用于防火墙
              #      日志 slf4j logback
              #      log4j
            #      log4j2
            # 配置多个英文逗号分隔
            filters: stat,wall,log4j
            share-prepared-statements: true
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录 SQL优化
            connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
            # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
            web-stat-filter:
              #是否启用StatFilter默认值false
              enabled: true
              # 拦截所有的
              url-pattern: /*
              # 排除一些不必要的url，比如*:js,/jslib/*等等:
              exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico, /druid/*"
              # 关闭和开启session 统计功能 默认关闭
              #        session-stat-enable: true
              # sessionStatMaxCount是1000个
              #        session-stat-max-count: 1000
              # 配置principalSessionName，使得druid能够知道当前的session的用户是谁
              #        principal-session-name:
              # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
            stat-view-servlet:
              # 是否启用StatViewServlet默认值true
              enabled: true
              url-pattern: /druid/*
              # 界面上有一个重置功能 执行这个操作之后，会导致所有计数器清零，重新计数 建议false
              reset-enable: false
              # 登录的后台的用户名,密码
              login-username: admin
              login-password: admin
        ct-activity:
          url: jdbc:mysql://39.106.39.129:3306/ct-activity?useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 1311150301
          type: com.alibaba.druid.pool.xa.DruidXADataSource
          driverClassName: com.mysql.jdbc.Driver
          druid:
            initial-size: 3
            max-active: 8
            min-idle: 2
            max-wait: -1
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall,log4j
            share-prepared-statements: true
        ct-coupon:
          url: jdbc:mysql://39.106.39.129:3306/ct-coupon?useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 1311150301
          type: com.alibaba.druid.pool.xa.DruidXADataSource
          driverClassName: com.mysql.jdbc.Driver
          druid:
            initial-size: 3
            max-active: 8
            min-idle: 2
            max-wait: -1
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall,log4j
            share-prepared-statements: true
        ct-credit:
          url: jdbc:mysql://39.106.39.129:3306/ct-credit?useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 1311150301
          type: com.alibaba.druid.pool.xa.DruidXADataSource
          driverClassName: com.mysql.jdbc.Driver
          druid:
            initial-size: 3
            max-active: 8
            min-idle: 2
            max-wait: -1
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall,log4j
            share-prepared-statements: true
        ct-lottery:
          url: jdbc:mysql://39.106.39.129:3306/ct-lottery?useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 1311150301
          type: com.alibaba.druid.pool.xa.DruidXADataSource
          driverClassName: com.mysql.jdbc.Driver
          druid:
            initial-size: 3
            max-active: 8
            min-idle: 2
            max-wait: -1
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall,log4j
            share-prepared-statements: true
        ct-order:
          url: jdbc:mysql://39.106.39.129:3306/ct-order?useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 1311150301
          type: com.alibaba.druid.pool.xa.DruidXADataSource
          driverClassName: com.mysql.jdbc.Driver
          druid:
            initial-size: 3
            max-active: 8
            min-idle: 2
            max-wait: -1
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall,log4j
            share-prepared-statements: true
        ct-package:
          url: jdbc:mysql://39.106.39.129:3306/ct-package?useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 1311150301
          type: com.alibaba.druid.pool.xa.DruidXADataSource
          driverClassName: com.mysql.jdbc.Driver
          druid:
            initial-size: 3
            max-active: 8
            min-idle: 2
            max-wait: -1
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall,log4j
            share-prepared-statements: true
        ct-finance:
          url: jdbc:mysql://39.106.39.129:3306/ct-finance?useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 1311150301
          type: com.alibaba.druid.pool.xa.DruidXADataSource
          driverClassName: com.mysql.jdbc.Driver
          druid:
            initial-size: 3
            max-active: 8
            min-idle: 2
            max-wait: -1
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall,log4j
            share-prepared-statements: true




  transaction:
    default-timeout: -1
  jta:
    log-dir: classpath:tx-logs
    transaction-manager-id: txManager