server:
  port: 8081
eureka:
  instance:
    instance-id: localhost:${server.port}
  client:
    register-with-eureka: true #指定是否向注册中心注册自己
    fetch-registry: true #指定客户端是否可以获取eureka注册信息
    service-url: #暴露服务中心地址
      defaultZone: http://localhost:8888/eureka
    registry-fetch-interval-seconds: 30
    cache-refresh-executor-exponential-back-off-bound: 10
spring:
  application:
    name: serviceA

management:
  endpoints:
    web:
      exposure:
        include: "*" #开启所有监控终端
  endpoint:
    shutdown:
      enabled: true # 开启shutdown监控终端