server:
  port: 8002


spring:
  transaction:
    default-timeout: -1
mybatis-plus:
  mapper-locations: classpath:/mappers/ct/*/*.xml

activity:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://39.106.39.129:3306/ct-activity?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1311150301
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 2
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
coupon:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://39.106.39.129:3306/ct-coupon?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1311150301
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 2
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
credit:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://39.106.39.129:3306/ct-credit?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1311150301
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 2
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
finance:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://39.106.39.129:3306/ct-finance?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1311150301
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 2
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
lottery:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://39.106.39.129:3306/ct-lottery?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1311150301
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 2
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
order:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://39.106.39.129:3306/ct-order?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1311150301
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 2
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
package:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    url: jdbc:mysql://39.106.39.129:3306/ct-package?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1311150301
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 2
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
jta:
  log-dir: classpath:tx-logs
  transaction-manager-id: txManager
